name: Move_Radigo-Files

on:
  workflow_dispatch: # 手動実行を許可
    inputs:
      dry_run:
        description: 'Run in dry-run mode'
        required: false
        default: false
        type: boolean
  #schedule:
  #  - cron: '0 0 * * *' # 毎日午前0時 (UTC) に実行 (JST 午前9時)

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      id: setup-python # ステップIDを追加
      uses: actions/setup-python@v3
      with:
        python-version: '3.x' # 適切なPythonバージョンを指定

    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ steps.setup-python.outputs.python-version }}-pydrive2-cache # setup-pythonの出力バージョンを使用
        restore-keys: |
          ${{ runner.os }}-pip-${{ steps.setup-python.outputs.python-version }}-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pydrive2

    - name: Create settings.yaml
      run: |
        echo "client_config_backend: settings" > settings.yaml
        echo "client_config:" >> settings.yaml
        echo "  client_id: ${{ secrets.GOOGLE_CLIENT_ID }}" >> settings.yaml
        echo "  client_secret: ${{ secrets.GOOGLE_CLIENT_SECRET }}" >> settings.yaml
        echo "save_credentials: True" >> settings.yaml
        echo "save_credentials_backend: file" >> settings.yaml
        echo "save_credentials_file: credentials.json" >> settings.yaml
        echo "get_refresh_token: True" >> settings.yaml
        echo "oauth_scope:" >> settings.yaml
        echo "  - https://www.googleapis.com/auth/drive" >> settings.yaml
        echo "output_folder_id: ${{ secrets.OUTPUT_FOLDER_ID }}" >> settings.yaml
        echo "target_folder_path: ${{ secrets.TARGET_FOLDER_PATH }}" >> settings.yaml
      env:
        GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
        GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
        OUTPUT_FOLDER_ID: ${{ secrets.OUTPUT_FOLDER_ID }}
        TARGET_FOLDER_PATH: ${{ secrets.TARGET_FOLDER_PATH }}

    - name: Create credentials.json
      run: |
        echo '${{ secrets.GOOGLE_CREDENTIALS_JSON }}' > credentials.json
      env:
        GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}

    - name: Run script
      run: |
        if [[ "${{ github.event.inputs.dry_run }}" == "true" ]]; then
          python radio_furiwake.py --dry-run
        else
          python radio_furiwake.py
        fi
